### ISSUE TITLE
Homepage images clash in some horizontal mobile orientations

### ISSUE THREAD

**Issue by STBoyden** [Authentura/codectrl-website#5]
![Screenshot_20220804-224445_DuckDuckGo.png](https://user-images.githubusercontent.com/25185976/182958321-f0f6b8e2-af43-4e46-8ad2-da833a7a0c74.png)

**Comment by rootEnginear** [comment]
Is this still available? If so could you assign this to me? I'll do a PR for this one.

**Comment by STBoyden** [comment]
Fantastic, assigning you now :)
